# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' stern_brocot_tree
NULL

#' first_coprime
NULL

#' nearby_coprime
NULL

#' rational_fractions
NULL

stern_brocot_tree <- function(x) {
    .Call(`_coprimer_stern_brocot_tree`, x)
}

first_coprime <- function(x, lower_uncertainty, upper_uncertainty) {
    .Call(`_coprimer_first_coprime`, x, lower_uncertainty, upper_uncertainty)
}

nearby_coprime <- function(x, lower_uncertainty, upper_uncertainty) {
    .Call(`_coprimer_nearby_coprime`, x, lower_uncertainty, upper_uncertainty)
}

rational_fractions <- function(x, x_ref, uncertainty) {
    .Call(`_coprimer_rational_fractions`, x, x_ref, uncertainty)
}

